blank_issues_enabled: false
contact_links:
  - name: DSPy documentation
    url: https://dspy.ai/
    about: Review guides, tutorials, and API reference before opening an issue.
  - name: 💬 DSPy Discord
    url: https://discord.gg/XCGy2WDCQB
    about: Ask usage questions, share ideas, or get real-time help from the community.
