---
name: Feature Request
description: Suggest a new feature or improvement for this project.
title: "[Feature]: "
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

  - type: checkboxes
    id: checklist
    attributes:
      label: Idea checklist
      options:
        - label: I have searched existing issues and discussions to avoid duplicates.
          required: true
        - label: This feature aligns with the project's goals and scope.
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
      description: Describe the user story or pain point you are trying to solve.
      placeholder: "Example: Our deployment workflow requires overriding the build command in multiple places..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Outline what you would like to see added or changed.
      placeholder: "Describe the API, CLI, docs, or behaviour you are proposing."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Explain how this change helps project users or maintainers (performance, usability, new workflows, etc.).
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: List any workarounds or related ideas you have explored.

  - type: dropdown
    id: contribution
    attributes:
      label: Are you able to contribute?
      options:
        - "Yes, I'd like to open a PR."
        - "Maybe, I'd need guidance."
        - "No, I just have a suggestion."

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, references, mock-ups, or anything else we should review.
